spring.application.name=forum-service

spring.data.mongodb.uri=${MONGODB_URI}

logging.level.ait.cohort46.post.service=INFO
logging.file.name=Log/app.log
logging.logback.rollingpolicy.max-file-size=10KB

password.period=60